version: "3"
services:
  web:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/template:/etc/nginx/template
      - ../nuxt3-app/.output/public:/var/www/html
    command: /bin/sh -c "DOLLAR=$$ envsubst < /etc/nginx/template/default.conf > /etc/nginx/conf.d/default.conf; nginx -g 'daemon off;' "
    environment:
      TZ: Asia/Tokyo
      SERVER_WEB_PORT: ${SERVER_WEB_PORT}
      SERVER_API_PORT: ${SERVER_API_PORT}
    ports:
      - "${SERVER_WEB_PORT}:${SERVER_WEB_PORT}"
